# Generated by Django 5.1 on 2026-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_food_items_orderitem_food_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
