# Generated by Django 5.1 on 2026-01-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_orderitem_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='checkout_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
