# Generated by Django 5.1 on 2026-01-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_remove_orderitem_total_price_orderitem_checkout_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='menu_item',
            new_name='food_item',
        ),
    ]
